// <auto-generated />
namespace Group1hospitalproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class appointdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appointdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202303211655395_appoint-date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
