// <auto-generated />
namespace Group1hospitalproject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removedeptdoc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedeptdoc));
        
        string IMigrationMetadata.Id
        {
            get { return "202303211646295_remove-dept-doc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
